services:
  db:
    image: postgres:15.3
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: weather_data
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/airflow_init.sql:/docker-entrypoint-initdb.d/airflow_init.sql
    networks:
      - my_network

  af:
    image: apache/airflow:3.3.0
    container_name: airflow_container
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@db:5432/airflow_db
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./api-request:/opt/airflow/api-request
      - /var/run/docker.sock:/var/run/docker.sock
    group_add:
      - '1001'
    depends_on:
      - db
    networks:
      - my_network
    command: >
      bash -c "airflow db migrate && airflow standalone"

  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:1.9.latest
    container_name: dbt_container
    volumes:
      - ./dbt/my_project:/usr/app
      - ./dbt:/root/.dbt
    working_dir: /usr/app
    environment:
      DBT_PROFILES_DIR: "/root/.dbt"
    depends_on:
      - db
    networks:
      - my_network
    command: run
    
networks:
  my_network:
    driver: bridge
 
  